services:
  nightbane:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nightbane
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nightbane.rule=Host(`nb.makl.xyz`) && !PathPrefix(`/signal`)"
      - "traefik.http.routers.nightbane.entrypoints=websecure"
      - "traefik.http.routers.nightbane.tls.certresolver=myresolver"
      - "traefik.http.services.nightbane.loadbalancer.server.port=80"

  nightbane-signal:
    build:
      context: ../lobby
      dockerfile: Dockerfile
    container_name: nightbane-signal
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nbsignal.rule=Host(`nb.makl.xyz`) && PathPrefix(`/signal`)"
      - "traefik.http.routers.nbsignal.entrypoints=websecure"
      - "traefik.http.routers.nbsignal.tls.certresolver=myresolver"
      - "traefik.http.services.nbsignal.loadbalancer.server.port=8765"

networks:
  proxy:
    external: true

